<div style="background-color: yellow; padding: 15px; border-radius: 10px;">
    <h1 style="color: black; text-align: center;">Healthcare Data Science Project</h1>
</div>

<div style="background-color:Teal; padding:15px; border-radius:10px">
<h2 style="color:black;">- I Table of contents</h2>
</div>

- [1-Business Problem](#1-Business-problem)
- [2-Libraries](#2-libraries)
- [3-Data loading](#3-data-loading)
- [4-EDA](#4-eda)
- [5-Feature engineering](#5-feature-engineering)
- [6-Train Test Split](#6-train-test-split)
- [7-Model Training](#7-model-training)
- [8-Model Evaluation](#8-model-evaluation)

- [1-Libraries](#1-libraries)
- [2-Data loading](#2-data-loading)
- [3-EDA](#3-eda)
- [4-Feature engineering](#4-feature-engineering)
- [5-Train Test Split](#5-train-test-split)
- [6-Model Training](#6-model-training)
- [7-Model Evaluation](#7-model-evaluation)

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">1- Formation of business problem</h2>
</div>

## How do patient arrival patterns (by hour of the day or day of the week) impact Patient Waittime, and how can we optimize hospital staffing during peak hours?

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">1- Libraries</h2>
</div>

In [4]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">2-Data loading</h2>
</div>

In [5]:
df = pd.read_csv("https://github.com/SunidhiHere/Healthcare-ML-Project/raw/main/healthcare_analytics_patient_flow_data.csv")

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">3-EDA</h2>
</div>

In [6]:
df.head()

,Patient Id,Patient Admission Date,Patient Admission Time,Merged,Patient Gender,Patient Age,Patient Race,Department Referral,Patient Admission Flag,Patient Satisfaction Score,Patient Waittime
0,780-96-6113,9/9/2024,9:25:00 AM,W. Breede,Female,63,African American,NaN,Not Admission,5.0,32
1,714-35-6722,9/9/2024,4:42:00 PM,Y. Baldetti,Male,31,Asian,Orthopedics,Not Admission,NaN,22
2,571-85-3714,9/9/2024,12:14:00 AM,M. Semerad,Male,75,White,General Practice,Not Admission,NaN,16
3,404-43-9499,9/9/2024,8:33:00 PM,K. Blaydes,Male,79,African American,General Practice,Admission,NaN,38
4,552-51-5855,9/9/2024,7:25:00 PM,F. Dickerson,Female,24,African American,NaN,Admission,NaN,36

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9216 entries, 0 to 9215
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Patient Id                  9216 non-null   object
 1   Patient Admission Date      9216 non-null   object
 2   Patient Admission Time      9216 non-null   object
 3   Merged                      9216 non-null   object
 4   Patient Gender              9216 non-null   object
 5   Patient Age                 9216 non-null   int64
 6   Patient Race                9216 non-null   object
 7   Department Referral         3816 non-null   object
 8   Patient Admission Flag      9216 non-null   object
 9   Patient Satisfaction Score  2517 non-null   float64
 10  Patient Waittime            9216 non-null   int64
dtypes: float64(1), int64(2), object(8)
memory usage: 792.1+ KB

In [8]:
df.describe()

       Patient Age  Patient Satisfaction Score  Patient Waittime
count  9216.000000                 2517.000000       9216.000000
mean     39.855143                    4.992054         35.259874
std      22.755125                    3.138043         14.735323
min       1.000000                    0.000000         10.000000
25%      20.000000                    2.000000         23.000000
50%      39.000000                    5.000000         35.000000
75%      60.000000                    8.000000         48.000000
max      79.000000                   10.000000         60.000000

In [9]:
df.shape

(9216, 11)

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">4-Feature Engineering</h2>
</div>

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">5-Train Test Split</h2>
</div>

<div style="background-color:Orange; padding:15px; border-radius:10px">
<h2 style="color:white;">6-Model Training</h2>
</div>

<div style="background-color:yellow; padding:15px; border-radius:10px">
<h2 style="color:black;">7-Model Evaluation</h2>
</div>